package tests;



/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import app.entities.EntityExample;

import static org.junit.Assert.*;

public class EntityTest {
    @Test public void testSomeLibraryMethod() {
        EntityExample classUnderTest = new EntityExample();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someMethod());
    }
}
